[tool.poetry]
name = "bybit-v5-client"
version = "0.0.5"
description = "Bybit V5 API client"
authors = ["chimpanzee <adm@cmpz.dev>"]
readme = "README.md"
packages = [{ include = "bybit_v5_client" }]

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"

[tool.poetry.group.test.dependencies]
pytest = "^7.2.2"
pytest-mock = "*"
pytest-cov = "^4.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
