[package]
name = "ultibi_core"
version= "0.1.6"
edition = "2021"
publish = false
license-file= "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive","derive"] }
polars = { version = "0.25.1", features = [
    "performant",
    "strings",
    "ndarray",
    "lazy",
    "is_in",
    "dtype-categorical",
    "serde",
    "csv-file",
    "diagonal_concat",
    "performant",
    "strings",
    "ndarray",
    "lazy",
    "is_in",
    "dtype-categorical",
    "serde",
    "csv-file",
    "diagonal_concat",
    "describe",
] }
serde_json = "1.0"
toml = "0.7.2"
once_cell = "1.12"
derivative = "2.2"
#AWS S3
aws-config = { version = "0.49.0", optional = true }
aws-sdk-s3 = { version = "0.19.0", optional = true }
tokio = { version = "1.21.2", features = ["rt-multi-thread"], optional = true }
futures = { version = "0.3", optional = true }
#Cache
#May be make optional
dashmap = "5.4.0"


[features]
default = []
aws_s3 = ["dep:aws-config", "dep:aws-sdk-s3", "dep:tokio", "dep:futures"]
