[build-system]
requires = [
    "setuptools>=42",
    "wheel",
]
build-backend="setuptools.build_meta"

[project]
name = "django-oasis4-coffee-price"
version = "1.0.6-beta.0"
authors = [
    {name="Mario CerÃ³n", email="mario.ceron@cqinversiones.co"}
]
description = "Cadefihuila Coffee Price REST Services"
readme = "README.md"
license = {file="LICENSE"}
requires-python = ">=3.9"
classifiers = [
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3.9",
    "Development Status :: 4 - Beta",
    "Framework :: Django",
    "Framework :: Django :: 4.1",
    "Environment :: Web Environment",
    "Operating System :: OS Independent",
    "Topic :: Internet :: WWW/HTTP"
]
dependencies = [
    "Django>=4.1",
    "djangorestframework",
    "django-oasis4>=1.0.6",
    "zibanu-django",
    "celery>=5.2.7",
    "django-celery-beat"
]
keywords = [
    "django",
    "cadefihuila",
]