[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "secenv"
version = "0.14.0"
description = "A manager that can read all your secrets and generate environment values based on them"
readme = "README.md"
authors = [{ name = "Keltio Labs", email = "labs@keltio.fr" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
]
keywords = []
dependencies = [
    "boto3",
    "hvac",
    "PyYAML",
    "passpy",
]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = ["black", "pytest"]
deploy = ["build", "twine"]

[project.urls]
Homepage = "https://gitlab.com/keltiotechnology/keltio-products/secenv"

[project.scripts]
secenv = "secenv.__init__:main"

[tool.pytest.ini_options]
addopts = ["--import-mode=importlib"]
