[tool.poetry]
name = "bioto-client"
version = "0.1.7"
description = "A python CLI client for accessing Bioto data"
authors = ["Bioto <it@bioto.co>"]
readme = "README.md"

[tool.poetry.scripts]
bioto-client = "bioto_client.cli:app"

[tool.poetry.dependencies]
python = "^3.10"
typer = {extras = ["all"], version = "^0.7.0"}
requests = "^2.28.2"
python-dotenv = "^0.21.1"
pydantic = "^1.10.4"
auth0-python = "^4.0.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
flake8 = "^6.0.0"
responses = "^0.22.0"

[project.urls]
"Homepage" = "https://github.com/wearebioto/PyClient"
"Bug Tracker" = "https://github.com/wearebioto/PyClient/issues"

[tool.pytest.ini_options]
minversion = "6.0"
pythonpath = "src"
python_files = "test_*.py"
testpaths = [
    "tests",
]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"