[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "palonso_sales"
version = "0.0.1"
authors = [
    { name="palonso", email="pablo.alonso@gmail.com" },
]
description = "My customized ORM on Sales"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Palons0/sales"
"Bug Tracker" = "https://github.com/Palons0/sales/issues"