[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "azure_recommendations_9"
version = "0.1.9"
authors = [
  { name="dheeraj.banodha", email="dheeraj.banodha@impetus.com" },
]
description = "Provides Azure recommendations"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

#[project.urls]
#"Homepage" = ""
#"Bug Tracker" = ""