[tool.poetry]
name = "streambotapi"
version = "1.0.8"
description = "A WebSocket development server for interaction with StreamBot package"
authors = ["dr00 <andrewmeyer23@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/dr00-eth/StreamBotAPI"
keywords = ["chatgpt", "stream", "openai", "websocket", "flask", "socketio", "gpt", "python"]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.2.3"
flask-cors = "^3.0.10"
flask-socketio = "^5.3.2"
streambot = "^1.1.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
