[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "credential"
version = "0.0.1"
authors = [
  { name="Alejandro", email="agarrido@izertis.com" },
]
description = "A small credential handler app for django"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  'Django==4.1.3',
  'djangorestframework==3.14.0',
  'drf-yasg==1.21.4',
  'pillow==9.3.0',
  'pyjwt==2.6.0',
  'web3==5.31.3',
  'django-waffle==3.0.0',
  'celery==5.2.7',
  'django-jsonform==2.15.0',
]
[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = ["*.html"]
