[tool.poetry]
name = "webint-guests"
version = "0.0.5"
description = "manage website guests"
authors = ["Angelo Gladding <angelo@ragt.ag>"]
license = "BSD-2-Clause"
packages = [{include = "webint_guests"}]

[tool.poetry.plugins."webapps"]
guests = "webint_guests:app"

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
webint = ">=0.0"

[tool.poetry.group.dev.dependencies]
# gmpg = "^0.0"
bgq = {path="../bgq", develop=true}
gmpg = {path="../gmpg", develop=true}
indieauth = {path="../python-indieauth", develop=true}
newmath = {path="../newmath", develop=true}
sqlyte = {path="../sqlyte", develop=true}
webagt = {path="../webagt", develop=true}
webint = {path="../webint", develop=true}

# [[tool.poetry.source]]
# name = "main"
# url = "https://ragt.ag/code/pypi"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
